import { icon } from './icons.js';

// The tool registry — the single list the home page, the router, the search box
// and the "Continue to…" suggestions all read from.
//
// It lives in its own module so that a tool can import it (to name the tools it
// hands off to) without importing the app entry point back into itself.

export const CATEGORIES = {
  image: { name: 'Image', color: 'var(--c-image)' },
  video: { name: 'Video', color: 'var(--c-video)' },
  audio: { name: 'Audio', color: 'var(--c-audio)' },
  pdf: { name: 'PDF', color: 'var(--c-pdf)' },
  text: { name: 'Text & Writing', color: 'var(--c-text)' },
  study: { name: 'Study', color: 'var(--c-study)' },
  utility: { name: 'Everyday', color: 'var(--c-utility)' },
};

export const TOOLS = [
  // ---- image ----
  { id: 'compress-image', name: 'Compress Image', icon: icon('compress'), category: 'image',
    desc: 'Shrink photos to fit LMS upload limits while keeping quality.',
    load: () => import('./tools/compress-image.js') },
  { id: 'resize-image', name: 'Resize Image', icon: icon('resize'), category: 'image',
    desc: 'Resize by pixels or percent — ID photos, slides, submissions.',
    load: () => import('./tools/resize-image.js') },
  { id: 'crop-image', name: 'Crop Image', icon: icon('crop'), category: 'image',
    desc: 'Crop freely or to presets like 1:1 profile and 3:4 ID photo.',
    load: () => import('./tools/crop-image.js') },
  { id: 'convert-image', name: 'Convert Image', icon: icon('convert'), category: 'image',
    desc: 'JPG ↔ PNG ↔ WebP in bulk, right in your browser.',
    load: () => import('./tools/convert-image.js') },
  { id: 'image-to-pdf', name: 'Images → PDF', icon: icon('image'), category: 'image',
    desc: 'Turn photos of notes or homework into one clean PDF.',
    load: () => import('./tools/image-to-pdf.js') },
  { id: 'heic-to-jpg', name: 'HEIC to JPG', icon: icon('image'), category: 'image',
    desc: 'Turn iPhone photos into JPG so uploads stop getting rejected.',
    load: () => import('./tools/heic-to-jpg.js') },
  { id: 'image-text', name: 'Add Text to Image', icon: icon('edit'), category: 'image',
    desc: 'Label screenshots and caption photos before you hand them in.',
    load: () => import('./tools/image-text.js') },
  { id: 'rotate-image', name: 'Rotate Image', icon: icon('rotate'), category: 'image',
    desc: 'Straighten up sideways photos, a whole folder at a time.',
    load: () => import('./tools/rotate-image.js') },
  { id: 'watermark-image', name: 'Watermark Image', icon: icon('image'), category: 'image',
    desc: 'Stamp your name across a photo before you share it.',
    load: () => import('./tools/watermark-image.js') },
  { id: 'remove-background', name: 'Remove Background', icon: icon('image'), category: 'image',
    desc: 'Cut the background out of a photo, on your own device.',
    load: () => import('./tools/remove-background.js') },
  { id: 'blur-face', name: 'Blur Faces', icon: icon('image'), category: 'image',
    desc: 'Hide faces and plate numbers before a photo goes public.',
    load: () => import('./tools/blur-face.js') },
  { id: 'upscale-image', name: 'Enlarge Image', icon: icon('resize'), category: 'image',
    desc: 'Make a small image bigger without it turning to mush.',
    load: () => import('./tools/upscale-image.js') },
  { id: 'photo-editor', name: 'Photo Editor', icon: icon('image'), category: 'image',
    desc: 'Filters, frames and stickers — a quick edit in the browser.',
    load: () => import('./tools/photo-editor.js') },
  // ---- video ----
  { id: 'compress-video', name: 'Compress Video', icon: icon('compress'), category: 'video',
    desc: 'Shrink a video to fit an LMS, LINE or email size limit.',
    load: () => import('./tools/compress-video.js') },
  { id: 'trim-video', name: 'Trim Video', icon: icon('crop'), category: 'video',
    desc: 'Cut the dead air off the start and end of a clip.',
    load: () => import('./tools/trim-video.js') },
  { id: 'convert-video', name: 'Convert Video', icon: icon('convert'), category: 'video',
    desc: 'MOV, MKV or WebM → an MP4 that plays anywhere.',
    load: () => import('./tools/convert-video.js') },
  { id: 'resize-video', name: 'Resize Video', icon: icon('resize'), category: 'video',
    desc: 'Reframe to 9:16, 1:1 or 16:9 for reels, posts and slides.',
    load: () => import('./tools/resize-video.js') },
  { id: 'video-to-gif', name: 'Video → GIF', icon: icon('video'), category: 'video',
    desc: 'Turn a few seconds of video into a looping GIF.',
    load: () => import('./tools/video-to-gif.js') },
  { id: 'video-to-frames', name: 'Video → Photos', icon: icon('video'), category: 'video',
    desc: 'Save frames from a lecture recording as JPG or PNG.',
    load: () => import('./tools/video-to-frames.js') },
  { id: 'screen-recorder', name: 'Screen Recorder', icon: icon('video'), category: 'video',
    desc: 'Record your screen and voice for a presentation hand-in.',
    load: () => import('./tools/screen-recorder.js') },
  // ---- audio ----
  { id: 'extract-audio', name: 'Extract Audio', icon: icon('audio'), category: 'audio',
    desc: 'Pull the sound out of a lecture video as MP3 or M4A.',
    load: () => import('./tools/extract-audio.js') },
  { id: 'trim-audio', name: 'Trim Audio', icon: icon('crop'), category: 'audio',
    desc: 'Cut a recording down to the part you actually need.',
    load: () => import('./tools/trim-audio.js') },
  { id: 'convert-audio', name: 'Convert Audio', icon: icon('convert'), category: 'audio',
    desc: 'M4A, WAV or OGG → MP3, and shrink long recordings.',
    load: () => import('./tools/convert-audio.js') },
  { id: 'voice-recorder', name: 'Voice Recorder', icon: icon('mic'), category: 'audio',
    desc: 'Record a voice note or a presentation script, then trim it.',
    load: () => import('./tools/voice-recorder.js') },
  { id: 'enhance-voice', name: 'Enhance Voice', icon: icon('audio'), category: 'audio',
    desc: 'Clean up a recording in one press — hiss down, voice forward, volume fixed.',
    load: () => import('./tools/enhance-voice.js') },
  { id: 'noise-removal', name: 'Remove Noise', icon: icon('audio'), category: 'audio',
    desc: 'Cut fan hum, aircon hiss and mains buzz out of a recording.',
    load: () => import('./tools/noise-removal.js') },
  { id: 'normalize-audio', name: 'Fix Volume', icon: icon('audio'), category: 'audio',
    desc: 'Make quiet recordings loud and uneven ones level.',
    load: () => import('./tools/normalize-audio.js') },
  { id: 'audio-speed', name: 'Change Speed', icon: icon('audio'), category: 'audio',
    desc: 'Listen at 1.5× without the chipmunk voice — and save it that way.',
    load: () => import('./tools/audio-speed.js') },
  { id: 'silence-cut', name: 'Cut Silences', icon: icon('audio'), category: 'audio',
    desc: 'Trim the dead air out of a lecture recording automatically.',
    load: () => import('./tools/silence-cut.js') },
  { id: 'equalizer', name: 'Equalizer', icon: icon('audio'), category: 'audio',
    desc: 'Shape the sound — clearer voice, more bass, less harshness.',
    load: () => import('./tools/equalizer.js') },
  { id: 'audio-merge', name: 'Join Audio', icon: icon('merge'), category: 'audio',
    desc: 'Stitch voice memos and clips into one file.',
    load: () => import('./tools/audio-merge.js') },
  // ---- pdf ----
  { id: 'html-to-pdf', name: 'Lecture HTML → PDF', icon: icon('pdf'), category: 'pdf',
    desc: 'Turn HTML lectures into PDFs — every slide, ready for any PDF reader.',
    load: () => import('./tools/html-to-pdf.js') },
  { id: 'merge-pdf', name: 'Merge PDF', icon: icon('merge'), category: 'pdf',
    desc: 'Combine reports, cover pages and appendices into one file.',
    load: () => import('./tools/merge-pdf.js') },
  { id: 'split-pdf', name: 'Split PDF', icon: icon('split'), category: 'pdf',
    desc: 'Extract the pages you need, or split every page apart.',
    load: () => import('./tools/split-pdf.js') },
  { id: 'compress-pdf', name: 'Compress PDF', icon: icon('compress'), category: 'pdf',
    desc: 'Get big scanned PDFs under submission size limits.',
    load: () => import('./tools/compress-pdf.js') },
  { id: 'pdf-to-images', name: 'PDF → Images', icon: icon('pdf'), category: 'pdf',
    desc: 'Export slides or pages as JPG/PNG for notes and posts.',
    load: () => import('./tools/pdf-to-images.js') },
  { id: 'organize-pdf', name: 'Organize PDF', icon: icon('pdf'), category: 'pdf',
    desc: 'Reorder, rotate or delete pages with live thumbnails.',
    load: () => import('./tools/organize-pdf.js') },
  { id: 'watermark-pdf', name: 'Watermark PDF', icon: icon('pdf'), category: 'pdf',
    desc: 'Stamp a diagonal DRAFT, ID, or CONFIDENTIAL watermark on every page.',
    load: () => import('./tools/watermark-pdf.js') },
  { id: 'page-numbers-pdf', name: 'Page Numbers', icon: icon('pdf'), category: 'pdf',
    desc: 'Add page numbers to any PDF for thesis and report formatting rules.',
    load: () => import('./tools/page-numbers-pdf.js') },
  { id: 'rotate-pdf', name: 'Rotate PDF', icon: icon('rotate'), category: 'pdf',
    desc: 'Turn sideways scans the right way up — whole PDFs at once, no quality loss.',
    load: () => import('./tools/rotate-pdf.js') },
  { id: 'sign-pdf', name: 'Sign PDF', icon: icon('edit'), category: 'pdf',
    desc: 'Draw your signature once and drop it onto a form.',
    load: () => import('./tools/sign-pdf.js') },
  { id: 'crop-pdf', name: 'Crop PDF', icon: icon('crop'), category: 'pdf',
    desc: 'Trim the margins off a scan so it fills the page.',
    load: () => import('./tools/crop-pdf.js') },
  { id: 'edit-pdf', name: 'Edit PDF', icon: icon('edit'), category: 'pdf',
    desc: 'Add text, images and boxes straight onto a PDF page.',
    load: () => import('./tools/edit-pdf.js') },
  { id: 'ocr-pdf', name: 'OCR PDF', icon: icon('pdf'), category: 'pdf',
    desc: 'Make a scanned PDF searchable — 19 languages, up to 3 at once.',
    load: () => import('./tools/ocr-pdf.js') },
  { id: 'pdf-forms', name: 'Fill PDF Form', icon: icon('pdf'), category: 'pdf',
    desc: 'Fill in a university form and flatten it so it stays put.',
    load: () => import('./tools/pdf-forms.js') },
  { id: 'unlock-pdf', name: 'Unlock PDF', icon: icon('lock'), category: 'pdf',
    desc: 'Remove the password from a PDF you know the password to.',
    load: () => import('./tools/unlock-pdf.js') },
  { id: 'redact-pdf', name: 'Redact PDF', icon: icon('pdf'), category: 'pdf',
    desc: 'Black out an ID number so it is really gone, not just hidden.',
    load: () => import('./tools/redact-pdf.js') },
  { id: 'compare-pdf', name: 'Compare PDF', icon: icon('pdf'), category: 'pdf',
    desc: 'Spot what changed between two drafts of a report.',
    load: () => import('./tools/compare-pdf.js') },
  { id: 'pdf-to-markdown', name: 'PDF → Markdown', icon: icon('pdf'), category: 'pdf',
    desc: 'Pull a PDF into clean Markdown for your notes.',
    load: () => import('./tools/pdf-to-markdown.js') },
  { id: 'scan-to-pdf', name: 'Scan to PDF', icon: icon('camera'), category: 'pdf',
    desc: 'Photograph your notes with the camera and get a tidy PDF.',
    load: () => import('./tools/scan-to-pdf.js') },
  { id: 'word-to-pdf', name: 'Word → PDF', icon: icon('pdf'), category: 'pdf',
    desc: 'Turn a .docx into a PDF the LMS will accept.',
    load: () => import('./tools/word-to-pdf.js') },
  { id: 'excel-to-pdf', name: 'Excel → PDF', icon: icon('pdf'), category: 'pdf',
    desc: 'Turn a spreadsheet into a printable PDF table.',
    load: () => import('./tools/excel-to-pdf.js') },
  // ---- text ----
  { id: 'word-counter', name: 'Word Counter', icon: icon('text'), category: 'text',
    desc: 'Words, characters, sentences and reading time — live.',
    load: () => import('./tools/word-counter.js') },
  { id: 'citation-generator', name: 'Citation Generator', icon: icon('text'), category: 'text',
    desc: 'APA 7 and MLA 9 citations for websites, books and journals.',
    load: () => import('./tools/citation-generator.js') },
  // ---- study ----
  { id: 'gpa-calculator', name: 'GPA Calculator', icon: icon('study'), category: 'study',
    desc: 'Term and cumulative GPA on the standard university scale.',
    load: () => import('./tools/gpa-calculator.js') },
  { id: 'pomodoro', name: 'Focus Timer', icon: icon('clock'), category: 'study',
    desc: 'Pomodoro study sessions with breaks and a session count.',
    load: () => import('./tools/pomodoro.js') },
  // ---- utility ----
  { id: 'workflows', name: 'Workflows', icon: icon('utility'), category: 'utility',
    desc: 'Chain tools into one saved routine and run files through it in one go.',
    load: () => import('./tools/workflows.js') },
  { id: 'qr-generator', name: 'QR Code Maker', icon: icon('utility'), category: 'utility',
    desc: 'Share links and Wi-Fi with your group in one scan.',
    load: () => import('./tools/qr-generator.js') },
  { id: 'unit-converter', name: 'Unit Converter', icon: icon('utility'), category: 'utility',
    desc: 'Length, mass, temperature, data size and more.',
    load: () => import('./tools/unit-converter.js') },
];
