// Reproducible raster social card. No external fonts or image services.
import { createCanvas, loadImage } from '@napi-rs/canvas';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
const canvas = createCanvas(1200, 630);
const ctx = canvas.getContext('2d');
const gradient = ctx.createLinearGradient(0, 0, 1200, 630);
gradient.addColorStop(0, '#151927'); gradient.addColorStop(1, '#30275a');
ctx.fillStyle = gradient; ctx.fillRect(0, 0, 1200, 630);
ctx.fillStyle = '#8379fc'; ctx.fillRect(0, 0, 1200, 10);
ctx.drawImage(await loadImage(readFileSync('public/icon.svg')), 76, 65, 110, 110);
ctx.font = 'bold 62px sans-serif'; ctx.fillStyle = '#ffffff'; ctx.fillText('UniLab', 212, 145);
ctx.font = 'bold 65px sans-serif';
ctx.fillText('Every tool a student needs,', 76, 277);
ctx.fillText('in one place.', 76, 357);
ctx.font = '29px sans-serif'; ctx.fillStyle = '#d7d4f2';
ctx.fillText('PDFs  /  Images  /  Video  /  Audio', 80, 422);
ctx.fillStyle = '#ffffff'; ctx.font = 'bold 25px sans-serif';
ctx.fillText('Free. Private. No file uploads.', 80, 548);
ctx.fillStyle = '#bcb4ff'; ctx.font = '24px sans-serif';
ctx.textAlign = 'right'; ctx.fillText('unilab.ztvmm.live', 1120, 548);
mkdirSync('public/social', { recursive: true });
writeFileSync('public/social/unilab-v020.png', canvas.toBuffer('image/png'));
